# Generated by Django 4.0.5 on 2022-06-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
            ],
        ),
    ]
